name: Studio Deploy Development
on:
  push:
    branches:
      - development
jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Caching
        id: react-cache-build
        uses: actions/cache@v2
        with:
          path: |
            public
            .cache
            node_modules
          key: ${{ runner.os }}-react-studio-dappify-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-react-studio-dappify-
      - name: Install dependencies
        run: npm i --force
      - name: Build
        env: 
          SKIP_PREFLIGHT_CHECK: true
          REACT_APP_MORALIS_APP_ID: ${{ secrets.MORALIS_APP_ID_DEV }}
          REACT_APP_MORALIS_SERVER_URL: ${{ secrets.MORALIS_SERVER_URL_DEV }}
          REACT_APP_MORALIS_API_KEY: ${{ secrets.MORALIS_API_KEY }}
          REACT_APP_MAGIC: ${{ secrets.MAGIC }}
          REACT_APP_MICROPAPER_URL: "https://mirage-property-c46.notion.site/Micropaper-a0836d7575b0400a8362797c9b21731a" 
          REACT_APP_ROADMAP_URL: "https://app.dework.xyz/dappify-1"
          REACT_APP_CHANGELOG_URL: "https://mirage-property-c46.notion.site/Change-log-310735dc8fa44a0ab777feadf7558abd"
          REACT_APP_BLOG_URL: "https://medium.com/@dappify"
          REACT_APP_HOST_ENV: dev
          CI: false
          NODE_OPTIONS: "--max-old-space-size=8192"
        run: npm run build:cli
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy to S3
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          PROJECT_NAME: studio
        run: aws s3 sync build s3://dev.dappify.com/$PROJECT_NAME/ --region $AWS_REGION
      - name: Invalidate Cloudfront Cache
        env:
          CF_DIST: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID_DEV }}
        run: aws cloudfront create-invalidation --distribution-id $CF_DIST --paths '/*'